# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gdb-utils',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/gdb-utils',
                'lib_path': 'gdb_utils'},
  'syms': { 'gdb_utils.core': { 'gdb_utils.core.TeiUtils': ('core.html#teiutils', 'gdb_utils/core.py'),
                                'gdb_utils.core.TeiUtils.__init__': ('core.html#teiutils.__init__', 'gdb_utils/core.py'),
                                'gdb_utils.core.TeiUtils.download': ('core.html#teiutils.download', 'gdb_utils/core.py'),
                                'gdb_utils.core.TeiUtils.get_javascript': ('core.html#teiutils.get_javascript', 'gdb_utils/core.py'),
                                'gdb_utils.core.TeiUtils.get_tag_freq': ('core.html#teiutils.get_tag_freq', 'gdb_utils/core.py')}}}
